contact_links:
  - name: support forum
    url: https://github.com/nothings/stb/discussions/categories/q-a
    about: having trouble using an stb Api_and_Library_Learn? don't create an issue, post in the forum
