//
// Created by lenovo on 10/24/2023.
//

#ifndef LEARN_RECORD_MOUSEBUTTONCODES_H
#define LEARN_RECORD_MOUSEBUTTONCODES_H

#define YIC_MOUSE_BUTTON_1         0
#define YIC_MOUSE_BUTTON_2         1
#define YIC_MOUSE_BUTTON_3         2
#define YIC_MOUSE_BUTTON_4         3
#define YIC_MOUSE_BUTTON_5         4
#define YIC_MOUSE_BUTTON_6         5
#define YIC_MOUSE_BUTTON_7         6
#define YIC_MOUSE_BUTTON_8         7
#define YIC_MOUSE_BUTTON_LAST      YIC_MOUSE_BUTTON_8
#define YIC_MOUSE_BUTTON_LEFT      YIC_MOUSE_BUTTON_1
#define YIC_MOUSE_BUTTON_RIGHT     YIC_MOUSE_BUTTON_2
#define YIC_MOUSE_BUTTON_MIDDLE    YIC_MOUSE_BUTTON_3

#endif //LEARN_RECORD_MOUSEBUTTONCODES_H
